### ISSUE TITLE
Birth certs 1st milestone punch list

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/digital#268]
- [x] Quantity dropdown on review page
- [x] Date input field mask / validation
- [x] Remove "X" on review page, add "cancel and start over" link

**Comment by fionawhim** [comment]
Product is ok with date field being a single text field with "mm/dd/yyyy" input mask

**Comment by fionawhim** [comment]
Use the "Qty." combo box from death certificate page on the review step, but Jess to also test having a stepper.
